use anyhow::Result;

use crate::config::RequireInfo;

/// Values for the generated Luau module.
pub struct LuauModuleParams<'a> {
    pub module_ident: &'a str,
    pub require: Option<&'a RequireInfo>,
    pub cell_width: u32,
    pub cell_height: u32,
    pub columns: u32,
}

/// Generate a complete `.luau` module string.
///
/// With `require` set, emits `local X = require("…")` and `Sheets[i] = X["key"]`.
/// Without it, emits `Sheets[i] = "key"` (plain strings).
pub fn render_module(
    p: &LuauModuleParams<'_>,
    sheet_keys: &[String],
    entries: &[(String, u32, u32)],
) -> Result<String> {
    let mut out = String::new();
    out.push_str("-- This file is automatically @generated by Spritepack.\n");
    out.push_str("-- It is not intended for manual editing.\n");
    out.push('\n');

    if let Some(req) = p.require {
        out.push_str(&format!(
            "local {} = require(\"{}\")\n\n",
            req.local_name, req.require_path
        ));
    }

    out.push_str(&format!("local {} = {{\n", p.module_ident));
    out.push_str("\tSheets = {\n");

    for (i, key) in sheet_keys.iter().enumerate() {
        let sheet_idx = i + 1;
        let escaped = escape_luau_table_string_key(key);
        if let Some(req) = p.require {
            let nesting: String = req
                .nesting_keys
                .iter()
                .map(|k| format!("[\"{}\"]", escape_luau_table_string_key(k)))
                .collect();
            out.push_str(&format!(
                "\t\t[{sheet_idx}] = {}{nesting}[\"{escaped}\"],\n",
                req.local_name
            ));
        } else {
            out.push_str(&format!("\t\t[{sheet_idx}] = \"{escaped}\",\n"));
        }
    }

    out.push_str("\t},\n");
    out.push_str("\tCellSize = {\n");
    out.push_str(&format!("\t\tWidth = {},\n", p.cell_width));
    out.push_str(&format!("\t\tHeight = {},\n", p.cell_height));
    out.push_str("\t},\n");
    out.push_str(&format!("\tColumns = {},\n", p.columns));
    out.push_str("\tImageEntries = {\n");

    for (clean_name, index, sheet) in entries {
        out.push_str(&format!(
            "\t\t[\"{clean_name}\"] = {{ index = {index}, sheet = {sheet} }},\n"
        ));
    }

    out.push_str("\t},\n");
    out.push_str("}\n\n");
    out.push_str(&format!("return {}\n", p.module_ident));
    Ok(out)
}

/// PascalCase identifier for `local MySheet = …` from a folder name.
pub fn folder_to_module_ident(folder_name: &str) -> String {
    let parts: Vec<&str> = folder_name
        .split(|c: char| !c.is_alphanumeric())
        .filter(|s| !s.is_empty())
        .collect();

    if parts.is_empty() {
        return "SpriteSheet".to_string();
    }

    parts
        .into_iter()
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

/// Escape a key for use inside Luau `["..."]` (double-quoted string).
pub fn escape_luau_table_string_key(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '\\' => "\\\\".to_string(),
            '"' => "\\\"".to_string(),
            c => c.to_string(),
        })
        .collect()
}

/// Sheet key names: `{folder}_1`, `{folder}_2`, etc.
pub fn sheet_asset_keys(folder_name: &str, sheet_count: usize) -> Vec<String> {
    (1..=sheet_count)
        .map(|i| format!("{folder_name}_{i}"))
        .collect()
}

/// Clean key like SpriteMaker.py: basename without extension, drop `.` and spaces.
pub fn clean_entry_name(file_stem: &str) -> String {
    file_stem.replace(['.', ' '], "")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::RequireInfo;

    #[test]
    fn module_with_require_no_nesting() {
        let req = RequireInfo {
            require_path: "@game/ReplicatedStorage/Test/FromAsphalt".into(),
            local_name: "FromAsphalt".into(),
            nesting_keys: vec![],
        };
        let p = LuauModuleParams {
            module_ident: "TestSheet",
            require: Some(&req),
            cell_width: 128,
            cell_height: 128,
            columns: 8,
        };
        let s = render_module(
            &p,
            &["TestSheet_1".to_string()],
            &[("Sprite_A".to_string(), 1, 1)],
        )
        .unwrap();
        assert!(s.starts_with("-- This file is automatically @generated by Spritepack."));
        assert!(
            s.contains("local FromAsphalt = require(\"@game/ReplicatedStorage/Test/FromAsphalt\")")
        );
        assert!(s.contains("[1] = FromAsphalt[\"TestSheet_1\"],"));
        assert!(s.contains("return TestSheet"));
    }

    #[test]
    fn module_with_require_nested() {
        let req = RequireInfo {
            require_path: "@game/ReplicatedStorage/Shared/Assets/ImagesIds".into(),
            local_name: "ImagesIds".into(),
            nesting_keys: vec!["Spritesheets".into()],
        };
        let p = LuauModuleParams {
            module_ident: "TestSheet",
            require: Some(&req),
            cell_width: 128,
            cell_height: 128,
            columns: 8,
        };
        let s = render_module(
            &p,
            &["TestSheet_1".to_string(), "TestSheet_2".to_string()],
            &[("Sprite_A".to_string(), 1, 1)],
        )
        .unwrap();
        assert!(s.contains(r#"[1] = ImagesIds["Spritesheets"]["TestSheet_1"],"#));
        assert!(s.contains(r#"[2] = ImagesIds["Spritesheets"]["TestSheet_2"],"#));
    }

    #[test]
    fn module_without_require() {
        let p = LuauModuleParams {
            module_ident: "TestSheet",
            require: None,
            cell_width: 64,
            cell_height: 64,
            columns: 4,
        };
        let s = render_module(
            &p,
            &["TestSheet_1".to_string(), "TestSheet_2".to_string()],
            &[("Sprite_A".to_string(), 1, 1)],
        )
        .unwrap();
        assert!(!s.contains("require("));
        assert!(s.contains("[1] = \"TestSheet_1\","));
        assert!(s.contains("[2] = \"TestSheet_2\","));
    }

    #[test]
    fn folder_to_module_ident_basic() {
        assert_eq!(folder_to_module_ident("test-sheet"), "TestSheet");
        assert_eq!(folder_to_module_ident("brain_rot"), "BrainRot");
    }

    #[test]
    fn sheet_asset_keys_multi() {
        assert_eq!(sheet_asset_keys("Foo", 3), vec!["Foo_1", "Foo_2", "Foo_3"]);
    }
}
